### PR TITLE
add css color names classes

### PR DESCRIPTION
**Pull request by yasser-sobhy**
added common CSS color names. I think they may be useful

### CODE REVIEW

**Comment by Nishchit14** [comment]
Thank you @yasser-sobhy, it would be good help :)

**Comment by Nishchit14** [comment]
@yasser-sobhy, Can you please update readme file with the color class name?

**Comment by yasser-sobhy** [comment]
Of course, I will update it today

**Comment by Nishchit14** [comment]
Also, CSS file is being generated from SCSS file compilation.

So you need to put those classes in https://github.com/Nishchit14/WhiteCss/blob/master/sass/utilities/_color.scss file. I'll compile and merge it later. If possible then please update it or I'll do it my self later.

**Comment by yasser-sobhy** [comment]
Ok, I will try to manage this today and update both files.

**Comment by yasser-sobhy** [comment]
@Nishchit14  I have updated both files, sorry for being late.

**Comment by Nishchit14** [comment]
Thank you for your contribution 👍

**Pull request merged**
